<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="4" passed="3" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-10-30T16:15:41 EET" name="Default suite" finished-at="2024-10-30T16:16:52 EET" duration-ms="70844">
    <groups>
    </groups>
    <test started-at="2024-10-30T16:15:41 EET" name="Default test" finished-at="2024-10-30T16:16:52 EET" duration-ms="70844">
      <class name="Storetest">
        <test-method is-config="true" signature="setup()[pri:0, instance:Storetest@1b765a2c]" started-at="2024-10-30T16:15:41 EET" name="setup" finished-at="2024-10-30T16:15:51 EET" duration-ms="9299" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="signup()[pri:1, instance:Storetest@1b765a2c]" started-at="2024-10-30T16:15:51 EET" name="signup" finished-at="2024-10-30T16:16:03 EET" duration-ms="12505" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- signup -->
        <test-method signature="logout()[pri:2, instance:Storetest@1b765a2c]" started-at="2024-10-30T16:16:03 EET" name="logout" finished-at="2024-10-30T16:16:14 EET" duration-ms="10429" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logout -->
        <test-method signature="login()[pri:3, instance:Storetest@1b765a2c]" started-at="2024-10-30T16:16:14 EET" name="login" finished-at="2024-10-30T16:16:31 EET" duration-ms="17199" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login -->
        <test-method signature="selectitems()[pri:4, instance:Storetest@1b765a2c]" started-at="2024-10-30T16:16:31 EET" name="selectitems" finished-at="2024-10-30T16:16:52 EET" duration-ms="21116" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [https://automationteststore.com/3] but found [https://automationteststore.com/]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [https://automationteststore.com/3] but found [https://automationteststore.com/]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at Storetest.selectitems(Storetest.java:189)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- selectitems -->
      </class> <!-- Storetest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
